INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H
.DATA

.CODE

MAIN PROC
    MOV BX, 10
    
    CMP BX, 100
    JGE IF1 ; COMPARE GREATER OR EQUAL TO 100
    
    CMP BX, 80
    JGE IF2 ; COMPARE GREATER OR EQUAL TO 80
    
    CMP BX, 60
    JGE IF3 ; COMPARE GREATER OR EQUAL TO 60
    
    CMP BX, 40
    JGE IF4 ; COMPARE GREATER OR EQUAL TO 40 
    
    CMP BX, 20
    JGE IF5 ; COMPARE GREATER OR EQUAL TO 20
    
    JMP ELSE
    
    IF1:
    PRINTN "NUMBER IS GREATER THAN OR EQUAL 100"
    JMP END_IF  
    
    IF2:
    PRINTN "NUMBER IS GREATER THAN OR EQUAL 80"
    JMP END_IF
    
    IF3:
    PRINTN "NUMBER IS GREATER THAN OR EQUAL 60"
    JMP END_IF
    
    IF4:
    PRINTN "NUMBER IS GREATER THAN OR EQUAL 40"
    JMP END_IF
    
    IF5:
    PRINTN "NUMBER IS GREATER THAN OR EQUAL 20"
    JMP END_IF 
    
    ELSE:
    PRINTN "NUMBER IS LESS THAN 20"
    JMP END_IF
    
    END_IF:
    MOV AX, 4CH
    INT 21H
    MAIN ENDP
END MAIN